export const todoConstants = {
  ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  ADD_TODO_FAILURE: "ADD_TODO_FAILURE",

  REMOVE_TODO_REQUEST: "REMOVE_TODO_REQUEST",
  REMOVE_TODO_SUCCESS: "REMOVE_TODO_SUCCESS",
  REMOVE_TODO_FAILURE: "REMOVE_TODO_FAILURE",

  TOGGLE_TODO_REQUEST: "TOGGLE_TODO_REQUEST",
  TOGGLE_TODO_SUCCESS: "TOGGLE_TODO_SUCCESS",
  TOGGLE_TODO_FAILURE: "TOGGLE_TODO_FAILURE",

  EDIT_TODO_REQUEST: "EDIT_TODO_REQUEST",
  EDIT_TODO_SUCCESS: "EDIT_TODO_SUCCESS",
  EDIT_TODO_FAILURE: "EDIT_TODO_FAILURE",
};
